; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Sat Mar 29 2025 14:11:29 GMT-0600 (Mountain Daylight Time)

M116 P0 ; wait for tool temperatures to be reached
